OPTS = -Wall -O3 -DNDEBUG
# OPTS = -Wall -g -O0

all: solve1 solve2

solve1: solve1.cc Makefile
	clang++ --std=c++17 $(OPTS) -o solve1 solve1.cc

solve2: solve2.cc Makefile
	clang++ --std=c++17 $(OPTS) -o solve2 solve2.cc
